analyzer/testdata/src/gocritic/f1.go
analyzer/testdata/src/gocritic/gocritic.rules.go
dsl/fluent/dsl.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/runner.go

Can be called after Report() to specify
which named submatch should be a report target.

all: location overriding method At()

---

rules.go

Empty string check suggested misstyped solution.

Fix empty string check suggestions

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/rules.go
rules.go

It also supports a simple fix that embeds an error value inside a struct
as it was done in https://github.com/google/syzkaller/commit/b4680d8341733f48295ccf188f109cf69027a3f9

rules.go: detect error used as underlying type for a named type

---

docs/gorules.md

Fixed typo: `arguements -> arguments`

docs: gorules: arguement -> argument

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/rules.go
ruleguard/typematch/typematch.go
ruleguard/typematch/typematch_test.go

Whenever rune is used, int32 is implied.
Whenever byte is used, uint8 is implied.
Fixes #58

ruleguard: support builtin type aliases (rune, byte)

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/filtertest/rules.go
ruleguard/typematch/typematch.go

"error" type is *types.Named, but it doesn't have the Package.
This can lead to a nil pointer dereference if we don't handle that case.
Since we never emit opNamed for builtin types, we can fix the
problem by doing an early "return false" for types without a package.
Fixes #61

ruleguard/typematch: handle builtin types in opNamed correctly

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/rules.go
ruleguard/runner.go

It does make sense to truncate output when printing the
suggestions to the stdout. It's bad if we try to apply
the truncated suggestions to a file though, it leads
to a broken syntax with meta variables inserted instead
of the actual replacements.
1. For the command-line output, increase the width limit to 60 (instead of 40).
2. When applying -fix suggestions, ignore the width limit.
Fixes #57

ruleguard: ignore match expr width limit for suggestions

---

analyzer/analyzer.go
ruleguard/gorule.go
ruleguard/merge.go
ruleguard/parser.go
ruleguard/ruleguard.go
ruleguard/runner.go

-rules flag becomes a comma-separated list of rule filenames.
If only one filename is provided, no effects will be noticed.
If more than one filenames are provided, they are merged
into one rule set that combines all rules.
To avoid information loss, we pass GoRuleInfo object to the
Report() callback, so the application can figure out which
file provided a rule that triggered.
As a demonstration, cmd/ruleguard now appends the "(filename)"
suffix to the warning messages when executed with multiple rule files.
The new ruleguard.MergeRuleSets() function can be used in
integrations like https://github.com/go-critic/go-critic/pull/947

all: added support for multi-file rule sets

---

rules.go

Needed to match the following code:
func rotate_right(v uint64, k uint) uint64 {
return (v >> k) | (v << (64 - k))
}

rules.go: add parentheses to math/bits matcher rules

---

.gitignore
go.mod
go.sum
ruleguard/parser.go
ruleguard/parser_test.go

Parsing a rule with the form `(a && b) && c` fails because the there's no way of handling parenthesized expressions
- Adding a case statement to the parser so it handles correctly a parenthesized expression.
- Testing with a particular example.

Parsing parenthesized expressions

---

dsl/fluent/dsl.go

dsl/fluent: improve Var.Type doc

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/filtertest/rules.go
ruleguard/typematch/typematch.go
ruleguard/typematch/typematch_test.go

Now it's possible to use func types in ExprType.Is-like patterns
inside Where() clauses.
Function type patterns should not use param names.
This is illegal: func(x int) (res string, err error)
This is legal:   func(int) (string, error)
It's possible to use meta types:
func($t, $t) int - function of 2 same args returning int
func() $t - function of 0 args that returns anything
func($t) $t - function of 1 arg that returns a value of the same type
func($t1) $t2 - function of 1 arg returning 1 result
Refs #80

ruleguard/typematch: implement func type patterns

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/rules.go
rules.go

Refs https://github.com/go-critic/go-critic/issues/836

rules.go: add exprUnparen rule

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/negative_tests.go
analyzer/testdata/src/extra/rules.go
rules.go

Ported from the go-critic linter.

rules.go: add badLock rule

---

ruleguard/typematch/typematch.go
ruleguard/typematch/typematch_test.go

struct{$*_} - arbitrary struct
struct{$_; $_} - struct of any 2 fields
struct{$x; $x} - struct of 2 fields of type $x
struct{$*_; $x} - struct that ends with $x-typed field
struct{$x; $*_} - struct that starts with $x-typed field
struct{$*_; $x; $*_} - struct that contains $x-typed field
This is not a direct solution for https://twitter.com/dgryski/status/1317245210041012224,
but it makes us get a little closer to it.
There are several interpretations of Type.Contains() and we need
to decide what should be traversed and whatnot (and how deep).
Until we decide on the exact Type.Contains() semantics, struct
type pattern matching can be a temporary solution to this problem.
I'll add analyzer tests later to see whether it really can be
used in the requested context. I would expect that we …

ruleguard/typematch: implement struct type pattern matching

---

analyzer/testdata/src/filtertest/f1.go

Undelying type definition is recursive, so calling
Underlying() is enough to resolve the entire type chain.

add another test for underlying type filter

---

rules.go

False-positive:
```
$ ruleguard.bin -rules rules.go go/... 
/usr/local/go/src/go/internal/gcimporter/bimport.go:241:35: suspicious duplicated args in types.Identical(a.Type(), b.Type())
```

fix bug in types.Identical rule

---

README.md
analyzer/analyzer.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/ruleguard.go
ruleguard/runner.go

When ruleguard is called with -debug-group=<string> arg,
it'll print rejected matches explanations to the stderr
for the specified rules group.
By default, this argument is an empty string that means "no debug".
Explanation includes:
* Submatch nodes (with types)
* Rejection reason (sometimes approx)
* Rejected node location
Here is an example of how explanations can look like:
example.go:4: rejected by rules.go:6 ($s type filter)
$s [10]int: a
example2.go:9: rejected by rules.go:8 ($s2 is const)
$s1 string: v1
$s2 string: ""
example2.go:7: rejected by rules.go:8 ($s1 is not const)
$s1 string: v1
$s2 string: v2
The debug output format is experimental and can change over time.
Any feedback is appreciated.
This change also adds Line:int and Group:string fields to the rules info.
Line is a …

ruleguard,analyzer: implement rules debugging

---

rules.go

```
// TODO returns a non-nil, empty Context. Code should use context.TODO when
// it's unclear which Context to use or it is not yet available (because the
// surrounding function has not yet been extended to accept a Context
// parameter). TODO is recognized by static analysis tools that determine
// whether Contexts are propagated correctly in a program.
func TODO() Context {
return todo
}
```
But last sentence was removed from the documentation in https://go-review.googlesource.com/c/go/+/130876/
Also issues https://github.com/golang/lint/pull/227 & https://github.com/golang/go/issues/16742

rules.go: add context.TODO

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/filtertest/rules.go
ruleguard/parser.go

Add a special case for `error` interface that is not part
of any package (it's builtin, so it's naturally unqualified).
Fixes #54

ruleguard: allow `error` type in `Implements()` filter

---

ruleguard/ruleguard_test.go
ruleguard/runner.go

If pattern had variables where one of them is a prefix of another,
there was a chance of incorrect results.
This change makes renderMessage() sort keys and interpolate longer
var names first, so we avoid that risk.
Scratch slice is used to do the sorting, so no extra allocations
is added. As successfull matching is far less frequent than
a failed (or rejected) match, sorting should not affect the performance.

ruleguard: fix interpolation of vars with common prefix

---

analyzer/testdata/src/gocritic/appendAssign.go
analyzer/testdata/src/gocritic/f1.go
analyzer/testdata/src/gocritic/rules.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/runner.go
ruleguard/utils.go

This is not a general solution to the problem, but it works.
Refs #125
Fixes #2
Fixes #3

ruleguard: allow Var.Value.Int() and Var.Text as RHS

---

analyzer/analyzer_test.go
analyzer/testdata/src/testvendored/file.go
analyzer/testdata/src/testvendored/rules.go
analyzer/testdata/src/testvendored/vendor/github.invalid/globex/logging/logger.go
ruleguard/typematch/typematch.go

Fix for #135.
I haven't looked into what are all the possible ways that a package can be imported, and how the type path would look like.

Handle type in a vendored directory

---

analyzer/testdata/src/regression/issue115.go
analyzer/testdata/src/regression/rules.go
ruleguard/debug_test.go
ruleguard/filters.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/runner.go

Refactored Where() filter parsing code.
Implemented || operator while at it.
Fixes #115 !(A && B) conditions now work properly
Fixes #26  A || B    conditions are now implemented

ruleguard: filter parsing improvements

---

ruleguard/runner.go

The GoRuleInfo.Line and GoRuleInfo.Group fields were not initialized correctly.

ruleguard: set GoRuleInfo fields before passing it to Report()

---

README.md
analyzer/analyzer.go
analyzer/testdata/src/extra/rules.go
analyzer/testdata/src/filtertest/rules.go
analyzer/testdata/src/gocritic/rules.go
analyzer/testdata/src/golint/rules.go
analyzer/testdata/src/namedtype/nested/rules.go
analyzer/testdata/src/namedtype/rules.go
analyzer/testdata/src/revive/rules.go
analyzer/testdata/src/suggest/rules.go
analyzer/testdata/src/testvendored/rules.go
docs/gorules.md
ruleguard/parser.go
rules.go

This feature was a mistake.
All rule groups should have a good name.
github.com/dgryski/semgrep-go doesn't use "_" rule groups,
so this breaking change should be tolerable.
We're getting closer to the 1.0, but we're not there yet.

all: forbid unnamed rule groups `func _()`

---

ruleguard/gorule.go
ruleguard/runner.go

We don't have any severity levels yet and there is 0
user requests for them.

ruleguard: remove unused severity field

---

analyzer/analyzer.go
ruleguard/debug_test.go
ruleguard/importer.go
ruleguard/parser.go
ruleguard/ruleguard.go
ruleguard/ruleguard_test.go

Allows to debug rules compile-time import issues.

ruleguard,analyzer: add -debug-imports flag

---

_test/install/gitclone/expected3.txt
_test/install/gitclone/expected4.txt
_test/install/gitclone/test.bash
analyzer/analyzer.go
ruleguard/parser.go
ruleguard/ruleguard.go

`-enable` and `-disable` are a comma separated lists.
It's not very convenient to specify a long list in bash,
but since most configuration is done in yaml (golangci-lint),
it should be somewhat readable:
disable: >-
A,
B,
C
Another option:
disable: "\
A,\
B,\
C"
Useful in combination with ruleguard modules.
Rules from modules can be disabled via -disable flag.
Both `-enable` and `-disable` flags can be debugged with
`-debug-enable-disable `flag (prints whether a group was enabled/disabled).
Refs #149

analyzer: add -enable and -disable flags

---

dsl/dsl.go
dsl/filter.go
dsl/types/ext.go
dsl/types/type_impl.go
dsl/types/types.go

`dsl/types` is a wrapper around `go/types` that provides the
minimal interface that is useful for custom filter.
We may add `dsl/ast` later to mimic `go/ast` as well for
node-related custom filters.
See https://github.com/quasilyte/go-ruleguard/issues/129#issuecomment-754300523
to get more context on what this is about.

dsl: add experimental API related to the custom filters

---

_test/install/gitclone_nobuildtag/Dockerfile
_test/install/gitclone_nobuildtag/expected.txt
_test/install/gitclone_nobuildtag/expected2.txt
_test/install/gitclone_nobuildtag/rules.go
_test/install/gitclone_nobuildtag/src/target.go
_test/install/gitclone_nobuildtag/test.bash
_test/install/gitclone_toolsgo/Dockerfile
_test/install/gitclone_toolsgo/expected.txt
_test/install/gitclone_toolsgo/expected2.txt
_test/install/gitclone_toolsgo/rules.go
_test/install/gitclone_toolsgo/src/target.go
_test/install/gitclone_toolsgo/test.bash
_test/install/gitclone_toolsgo/tools.go

Other tests add `github.com/quasilyte/go-ruleguard/dsl` as indirect
dependency, which may not be what people want as it may go
away after `go mod tidy`.
There are at least 2 ways to avoid that:
1. Use a `tools.go` idiom https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module
2. Do not add a `// +build ignore` tag to the `rules.go` file
Two new tests check that these options work as intended.

_test/install: add 2 tests for go modules based install

---

Makefile
analyzer/analyzer.go

`make build` is used for normal dev builds.
`make release` is used to prepare the release binaries.
Refs #179

analyzer: add optional version info (only when built with Make)

---

_test/install/gitclone/expected5.txt
_test/install/gitclone_nobuildtag/expected2.txt
_test/install/gitclone_toolsgo/expected2.txt
analyzer/analyzer.go

analyzer: don't print "e: " prefix in `-e` mode

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/gocritic/f1.go
analyzer/testdata/src/golint/file.go

Fixes #51.
---
I tried a few different approaches to do this automatically:
* Using an `analysis.Analyzer` didn't work because it wouldn't run on files under `testdata`.
* Parsing the files, modifying the comments in the `ast.File`, then rewriting the file using the `printer` package was no good either, because it also modified the formatting.
* Finally, I used a line-based approach with some simple regexps, and that did the trick.

Reduce metachar escaping in want regexps by using \Q

---

ruleguard/quasigo/eval_bench_test.go

When measuring `Call()` allocations, sometimes irrelevant
allocations happen in the process.
To avoid false positives, we do 5 attempts instead of 1.
If `Call()` does allocate, all 5 runs would show non-zero results.
Fixes #191

ruleguard/quasigo: fix flaky NoAllocs test

---

internal/mvdan.cc/gogrep/gogrep_test.go
internal/mvdan.cc/gogrep/match.go
internal/mvdan.cc/gogrep/parse.go

This way, we don't need to maintain a separate varInfo slice.
The decoding operation is cheap (and can probably be even more
efficient if we optimize it; but there is no need for that).

gogrep: encode varInfo into the ast.Ident directly

---

analyzer/testdata/src/extra/file.go
analyzer/testdata/src/extra/rules.go
internal/mvdan.cc/gogrep/gogrep.go
internal/mvdan.cc/gogrep/gogrep_test.go
internal/mvdan.cc/gogrep/match.go
ruleguard/parser.go

So the literals that are spelled differently, but have identical
underlying value can be matched.
"abc" = `abc`
0x0   = 0
0b11  = 3
'\n'  = '0x0a'
0.01  = .01
...etc
I'm planning to add a strict matching option for the DSL; but I need some use cases before that to see when it's useful (in which contexts and for what purpose). By default, all patterns are non-strict.

gogrep: add non-strict literal matching

---

rules/go.mod
rules/go.sum
rules/style.go
rules/testdata/style.go

Give a warning for these patterns:
fmt.Errorf("")
errors.New("")

rules: add emptyError rule

---

internal/mvdan.cc/gogrep/gogrep.go
internal/mvdan.cc/gogrep/gogrep_perf_test.go
internal/mvdan.cc/gogrep/gogrep_test.go
internal/mvdan.cc/gogrep/match.go
ruleguard/filters.go
ruleguard/gorule.go
ruleguard/ruleguard_test.go
ruleguard/runner.go

Since most patterns have less than 8 variables (usually, 1-4),
it's more efficient to use key-value slices instead of maps.
They also make memory reusing easier.
Even for 8 vars, slices are more efficient here.
```
name                           old time/op    new time/op    delta
Match/simpleLit-8                 217ns ± 3%     123ns ± 4%  -43.33%  (p=0.008 n=5+5)
Match/capture1-8                  652ns ± 7%     275ns ± 2%  -57.79%  (p=0.008 n=5+5)
Match/capture2-8                  950ns ± 0%     438ns ± 1%  -53.84%  (p=0.008 n=5+5)
Match/capture8-8                 3.89µs ± 5%    2.51µs ± 0%  -35.57%  (p=0.008 n=5+5)
Match/capture2same-8              947ns ± 2%     458ns ± 6%  -51.68%  (p=0.008 n=5+5)
Match/capture8same-8             3.42µs ± 2%    2.31µs ± 2%  -32.36%  (p=0.008 n=5+5) …
```

gogrep: use slices instead of maps for capture data

---

analyzer/testdata/src/regression/issue192.go
analyzer/testdata/src/regression/rules.go
internal/mvdan.cc/gogrep/gogrep.go
internal/mvdan.cc/gogrep/gogrep_test.go
internal/mvdan.cc/gogrep/match.go
ruleguard/runner.go

gogrep: save and restore wildcard positions during backtracking

---

ruleguard/parser.go

1. Changed parseError such that errors can be unwrapped if needed.
2. Create a sentinel ImportError such that callers can identify specific package import errors
Main change  is https://github.com/quasilyte/go-ruleguard/pull/217/files#diff-26106e9ba3277b0a6fb3ec1c696f2b4007d5b6c133575a2aa893b1260d5c7bd5R481-R483
This will make it possible to selectively process ruleguard errors in go-critic. In particular, this should make it possible to decide whether to skip or fail on parse error. I will raise a separate PR in go-critic.
This should help address https://github.com/quasilyte/go-ruleguard/issues/215

Change %v to %w so we can call Unwrap

---

ruleguard/parser.go
ruleguard/ruleguard_error_test.go

So we actually return an `*ImportError` instead of `*parseError`
which can't be examined on the caller side.

ruleguard: use parseError.error field for the returned error

---

_docs/dsl.md
analyzer/analyzer_test.go
analyzer/testdata/src/comments/rules.go
analyzer/testdata/src/comments/target.go
analyzer/testdata/src/comments/target_foo.go
go.mod
go.sum
ruleguard/debug_test.go
ruleguard/filters.go
ruleguard/gorule.go
ruleguard/match_data.go
ruleguard/parser.go
ruleguard/ruleguard_error_test.go
ruleguard/ruleguard_test.go
ruleguard/runner.go
ruleguard/utils.go

Most `Where()` filters work for comments as one would expect.
Named captures `?P<name>` can be accessed via `m["name"]`.
`Report()` and `Suggest()` interpolation can work with named captures.
The `$$` variable is bound to the entire regexp match (like `$0`).
Quickfixes work as well.
See #222

ruleguard: implement `MatchComment` function from the DSL

---

_docs/dsl.md
analyzer/analyzer.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/ruleguard.go
ruleguard/runner.go
rules/diag.go
rules/refactor.go
rules/style.go

A matcher function can now use 4 special pragmas:
* `gorules:summary` for a short description
* `gorules:before` for an example of a "bad code"
* `gorules:after` for a fixed code example
* `gorules:tags` for a list of custom tags
It's planned to make it possible for the integrating app
to access that information in a convenient way.
This PR is moslty about enabling on a parsing level.
These 4 fields (summary, before, after, tags) are selected
as something that is close to the `go-critic` checker documentation model.

ruleguard: add support for structured doc comments

---

analyzer/analyzer.go
go.mod
go.sum
ruleguard/engine.go
ruleguard/gorule.go
ruleguard/parser.go
ruleguard/ruleguard.go
ruleguard/runner.go

It returns the sorted slice of the groups that have been
loaded so far.

ruleguard: add Engine.LoadedGroups method

---

dsl/dsl.go

Line is a source code line number that contains this match.
If this match is multi-line, this is the first line number.
Refs #146

dsl: add Var.Line field

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/filtertest/rules.go
ruleguard/typematch/patternop_string.go
ruleguard/typematch/typematch.go
ruleguard/typematch/typematch_test.go

Makes it possible to match "any interface" type.

ruleguard/typematch: add `interface{$*_}` pattern support

---

analyzer/testdata/src/filtertest/f1.go
analyzer/testdata/src/filtertest/rules.go
analyzer/testdata/src/filtertest/utils.go
internal/gogrep/compile.go
internal/gogrep/gogrep.go
internal/gogrep/match.go
internal/gogrep/parse.go
internal/gogrep/slices.go
ruleguard/filters.go
ruleguard/utils.go

For patterns like `f($*args)` we can now apply a
`m["args"].Pure` filter to check whether **all** arguments are pure.
It works with most filters.
The current implementation is messy, but it will do for now.

ruleguard: handle variadic vars in filters properly

---

Makefile
analyzer/analyzer_test.go
analyzer/testdata/src/gocritic/rules.go
analyzer/testdata/src/localfunc/rules.go
analyzer/testdata/src/localfunc/target.go
analyzer/testdata/src/localfunc/target2.go
go.mod
go.sum
ruleguard/debug_test.go
ruleguard/irconv/irconv.go
ruleguard/ruleguard_error_test.go

This feature is useful for rule filters readability improvements.
Instead of copying a complex `Where()` expression several times,
one can now use a local function literal to define that filter
operation and use it inside `Where()` expressions.
Here is an example:
```go
func preferFprint(m dsl.Matcher) {
isFmtPackage := func(v dsl.Var) bool {
return v.Text == "fmt" && v.Object.Is(`PkgName`)
}
m.Match(`$w.Write([]byte($fmt.Sprint($*args)))`).
Where(m["w"].Type.Implements("io.Writer") && isFmtPackage(m["fmt"])).
Suggest("fmt.Fprint($w, $args)").
Report(`fmt.Fprint($w, $args) should be preferred to the $$`)
m.Match(`$w.Write([]byte($fmt.Sprintf($*args)))`).
Where(m["w"].Type.Implements("io.Writer") && isFmtPackage(m["fmt"])).
Suggest("fmt.Fprintf($w, $args)").
Report(`fmt.Fprintf($w, $args) …
```

ruleguard: add support for local functions

---

analyzer/analyzer.go
analyzer/testanalyzer/testanalyzer.go
ruleguard/ast_walker.go
ruleguard/debug_test.go
ruleguard/gorule.go
ruleguard/perf_test.go
ruleguard/ruleguard.go
ruleguard/runner.go

Pass a structure with a set of fields instead of
passing them as separate arguments.
This makes it easier to add more (potentially experimental)
match context arguments without breaking the API.
But this time we have to break the API once.
AST walker now saves current function name (and type name if it's
a method). This can be useful in filters later, so we can match
the current function name/type in `Where()` expressions.

ruleguard,analyzer: change Report() callback argument

---

analyzer/testdata/src/extra/file.go
ruleguard/ruleguard_test.go
ruleguard/runner.go

Instead of using variable names like `$x` when substitution
string is too long, truncate it to the max len.
So "some very long text" becomes "some v<...> text".
This is more user-friendly, as pattern variables are very
non-intuitive in most cases.

ruleguard: better text truncation in the rendered message

---

dsl/dsl.go

This allows a more concise and efficient checking for
numeric type ranges.
For instance, these are identical in semantics:
```
Type.Is("int") || Type.Is("int8") || Type.Is("int16") ||
Type.Is("int32") || Type.Is("int64")
=
Type.OfKind("int")
Type.Is("uint") || Type.Is("uint8") || Type.Is("uint16") ||
Type.Is("uint32") || Type.Is("uint64")
=
Type.OfKind("uint")
```
There are other useful kinds like "numeric", "signed", "unsigned", etc.

dsl: add Type.OfKind method

---

ruleguard/profiling/no_labels.go
ruleguard/profiling/with_labels.go
ruleguard/runner.go

When ruleguard is compiled with `--tags pproflabels`, profiling
will record per rules group labels, like `rules:groupname`.
This makes it easies to find the rules that may need to be
optimized or re-written in some other way.
Build tags protection is used to avoid the overhead in
the normal mode, when labels are not needed.
```
(pprof) tags
rules: Total 2.3s
410.0ms (18.14%): dupArg
350.0ms (15.49%): offBy1
250.0ms (11.06%): badLock
160.0ms ( 7.08%): argOrder
140.0ms ( 6.19%): equalFold
120.0ms ( 5.31%): redundantSprint
110.0ms ( 4.87%): wrapperFunc
90.0ms ( 3.98%): ioutilDeprecated
80.0ms ( 3.54%): preferFprint
70.0ms ( 3.10%): assignOp
60.0ms ( 2.65%): badCall
60.0ms ( 2.65%): externalErrorReassign
60.0ms ( 2.65%): stringXbytes
50.0ms ( 2.21%): valSwap
40.0ms ( 1.77%): …
```

ruleguard: add profiling labels support

---

analyzer/testdata/src/regression/issue115.go
analyzer/testdata/src/regression/issue339.go
analyzer/testdata/src/regression/rules.go
ruleguard/runner.go

This is probably a temporary and sub-optimal solution, but
it should do for now.
Since matches are much more rare than pattern misses,
we do the check under the `matched` condition.
Extra condition shouldn't make anything measurably slower there.
Fixes #339

ruleguard: continue pattern matching for multi-match patterns

---

ruleguard/ast_walker.go
ruleguard/runner.go

This allows us to get rid of `nodetag.FromNode()` call per
every ast node being processed.
name         old time/op  new time/op  delta
EngineRun-8  94.8µs ± 1%  82.8µs ± 0%  -12.70%  (p=0.000 n=10+8)

ruleguard: call Walk handler with nodetag

---

analyzer/testdata/src/regression/issue315.go
analyzer/testdata/src/regression/rules.go
ruleguard/filters.go
ruleguard/gorule.go
ruleguard/runner.go

ruleguard: improve FieldList and Field matching

---

analyzer/analyzer_test.go
analyzer/testdata/src/imports/f1.go
analyzer/testdata/src/imports/rules.go
go.mod
go.sum
ruleguard/ir_loader.go

This avoids any miscompiled patterns as well as allows
more precise matching of package symbols in function call contexts.

ruleguard: pass imports table to gogrep pattern compiler

---

dsl/dsl.go

HasMethod reports whether a type has a given method.
Unlike Implements(), it will work for both value and pointer types.
fn argument is a function signature, like `WriteString(string) (int, error)`.
It can also be in form of a method reference for importable types: `io.StringWriter.WriteString`.
To avoid confusion with Implements() method, here is a hint when to use which:
- If you want to check if it's possible to call F on x, use HasMethod().
- If you want to know if you can pass x as I interface, use Implements().
Refs #331

dsl: add ExprType.HasMethod()

---

ruleguard/ir_loader.go

Found by go-perfguard while running ruleguard under the golangci-lint.
golangci-lint does rules reloading per every package, so ir loading
speed does matter there.

ruleguard: do less copying in ir loader

---

analyzer/testdata/src/quickfix/rangeClause.go
analyzer/testdata/src/quickfix/rangeClause.go.golden
analyzer/testdata/src/quickfix/rules.go
ruleguard/ruleguard_test.go
ruleguard/runner.go

Given this pattern:
io.WriteString($w, $s)
And this input string:
io.WriteString(&buf, s)
With this replacement template:
$w.WriteString($s)
We'll get this result:
&buf.WriteString(s)
That's incorrect.
To avoid that, ruleguard attempts to fix some interpolated
expressions when it can understand the context.
In the cases above, it sees that variable is followed by `.`
while `$w` contains unary `&` expression. It knows that
`$w.x` is identical to `(&$w).w`, so we can simply insert
`buf` instead of `&buf` and get `buf.WriteString(s)`.
This greatly simplifies the creation of reliable rules
that just work.

ruleguard: autofix some interpolated expressions

---

ruleguard/ruleguard.go
ruleguard/runner.go

go-perfguard would benefit from longer truncate len thresholds.
We keep 60 as a default, but provide a way to override that.

ruleguard: make truncate len configurable

---

dsl/dsl.go

dsl: add submatches experimental API

---

analyzer/testdata/src/matching/file.go
analyzer/testdata/src/matching/rules.go
go.mod
go.sum
ruleguard/filters.go
ruleguard/ir/filter_op.gen.go
ruleguard/ir/gen_filter_op.go
ruleguard/ir_loader.go
ruleguard/irconv/irconv.go

all: implement sub-matches support

---

ruleguard/filters.go
ruleguard/gorule.go
ruleguard/runner.go

ruleguard: make sub-match gogrep state per-runner

---

.gitignore
Makefile
analyzer/analyzer_test.go
analyzer/testdata/src/regression/issue372.go
analyzer/testdata/src/regression/rules.go
ruleguard/filters.go
ruleguard/gorule.go
ruleguard/runner.go
ruleguard/typematch/typematch.go
ruleguard/typematch/typematch_test.go

This is the same trick we did with gogrep matcher.
The caller is supposed to pass the state that is not
shared between different threads.
For the most use cases, ruleguard has worker/runner based
concurrency, so it's easy to pass this state from the
worker that owns that state and doesn't share it with
other workers.
Also added some E2E tests that compile a ruleguard binary
with `-race` and run it using all test rules over the ruleguard
own source code. If any of these rules cause a data race,
this test fails.
To avoid the slower test times, I removed the `-race` from
the basic test as they do not involve any concurrent behavior
anyway, so it was just a waste of time.
Fixes #372
Fixes #368

ruleguard/typematch: use external matcher state

---

analyzer/analyzer.go
ruleguard/ir_loader.go
ruleguard/ruleguard.go

this change will allow easy filter rules by tags and other params in go-critic and 3rd part linters

change group filter signature

---

ruleguard/filters.go
ruleguard/quasigo/compile.go
ruleguard/quasigo/compile_test.go
ruleguard/quasigo/debug_info.go
ruleguard/quasigo/disasm.go
ruleguard/quasigo/eval.go
ruleguard/quasigo/eval_bench_test.go
ruleguard/quasigo/eval_test.go
ruleguard/quasigo/quasigo.go
ruleguard/runner.go

It makes it easier to implement quasigo funcs call
later on, so Go->quasigo and quasigo->quasigo can use
the same calling convention.
Note that args can be bound once (until env.Stack.Reset),
which is useful in plugins-like context when you pass
the same argument list to all user functions.

ruleguard/quasigo: pass args via ValueStack

---

analyzer/testdata/src/generics/rules.go
analyzer/testdata/src/generics/target.go
dsl/dsl.go
ruleguard/filters.go
ruleguard/utils.go

Extended the dsl documentation to reflect the change:
For expressions of unknown size, like type params in generics,
any filter using this operand will fail.
We're not using 0 as a fallback size to avoid the confusion with zero-sized values like `struct{}`.
See https://github.com/go-critic/go-critic/pull/1237
Fixes #406

ruleguard: fix sizeof filter for type params

---

README.md
_docs/rules.go

This section explains two common problems found when trying to run ruleguard:
- the dsl package not being available
- the dsl package not being included as a dependency of the module
Fixes #408
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@gmail.com>

Add troubleshooting sectipon to README.md

---

ruleguard/match_data.go
ruleguard/perf_test.go
ruleguard/ruleguard_test.go
ruleguard/runner.go
ruleguard/testdata/bench_target1.go
ruleguard/testdata/bench_target2.go
ruleguard/testdata/bench_target3.go

Do not use interface type for matchData since it caused heap allocations in both match and reject cases.

ruleguard: remove matchData allocations

---

ruleguard/typematch/typematch.go

We don't need to create `[]string` to compare the substring. This change reduces the amount of allocations when comparing named types via typematch package.

ruleguard/typematch: replace Split with Index to avoid allocs

---

go.mod
go.sum
ruleguard/engine.go
ruleguard/filters.go
ruleguard/nodepath.go
ruleguard/perf_test.go
ruleguard/ruleguard.go
ruleguard/runner.go

This allows more memory reuse between ruleguard engine executions.
Usually, app only needs one Engine object, which doesn't require any synchronization. For optimal execution, there should be N `RunnerState` objects, where N is number of concurrently executing goroutines that use same `Engine`.
name         old time/op    new time/op    delta
EngineRun-8     231µs ± 1%     197µs ± 0%  -14.72%  (p=0.000 n=9+10)
Issue412-8      205µs ± 1%     196µs ± 1%   -4.46%  (p=0.000 n=10+10)
name         old alloc/op   new alloc/op   delta
EngineRun-8    23.5kB ± 0%     9.1kB ± 0%  -61.26%  (p=0.000 n=8+8)
Issue412-8     9.54kB ± 0%    1.81kB ± 0%  -81.03%  (p=0.000 n=8+7)

ruleguard: introduce reusable runner state

---

analyzer/analyzer.go

For some test runs, this allows to allocate ~10 state objects instead of ~3000 without such pool.
Allocating a runner state is an expensive operation, we want to re-use as much state as possible to make ruleguard faster.
This patch should be used as an example of how ruleguard can be integrated into `go/analysis` framework while still having a reusable state between the engine runs.

analyzer: use sync.Pool to re-use ruleguard runner state

---

internal/goenv/goenv.go
internal/goenv/goenv_test.go
ruleguard/engine.go

Fixes https://github.com/quasilyte/go-ruleguard/issues/449

Make goenv parsing robust across go versions and OSes

---

internal/goenv/goenv.go
ruleguard/engine.go

Try to make the security linter happier:
```
Error: internal/goenv/goenv.go:10:14: G204: Subprocess launched with a potential tainted input or cmd arguments (gosec)
out, err := exec.Command("go", append([]string{"env"}, varNames...)...).CombinedOutput()
^
```

Make go env vars static

---

_docs/dsl.md
_docs/rules.go
analyzer/testdata/src/gocritic/f1.go
analyzer/testdata/src/gocritic/rules.go
dsl/dsl.go
ruleguard/ir_loader.go
ruleguard/quasigo/eval_test.go
ruleguard/ruleguard_test.go
ruleguard/textmatch/textmatch.go
ruleguard/utils.go

This PR corrects spelling mistakes in comments and reports.

ruleguard: fix typos

---

internal/xtypes/xtypes.go

This is a possible implementation of types.Type as of Go 1.22, and gets created by default starting in Go 1.23. This currently causes a panic when running under Go 1.23, because of the default `panic("unreachable")` in this switch statement.

Support alias types in typeIdentical()

---

.github/workflows/go.yml
.golangci.yml
Makefile
internal/xtypes/xtypes.go
ruleguard/irconv/irconv.go
ruleguard/irprint/irprint.go
ruleguard/quasigo/compile.go
ruleguard/ruleguard_error_test.go

- update golangci-lint to v1.60.2 (go1.23 support)
- fix golangci-lint configuration
- fix go-critic reports

chore: fix CI ang go1.22 support
