quasilyte/go-ruleguard

- analyzer/testdata/src/gocritic/f1.go
- analyzer/testdata/src/gocritic/gocritic.rules.go
- analyzer/testdata/src/gocritic/utils.go
- ruleguard/parser.go
- ruleguard/runner.go
- ruleguard/typematch/typematch.go
- ruleguard/typematch/typematch_test.go
- ruleguard/utils.go
> add pattern-based types matching

- analyzer/analyzer_test.go
- analyzer/testdata/src/extra/extra.rules.go
- analyzer/testdata/src/extra/file.go
- dsl/fluent/dsl.go
- ruleguard/parser.go
> all: implement ConvertibleTo type predicate

- analyzer/analyzer_test.go
- analyzer/testdata/src/namedtype/example.go
- analyzer/testdata/src/namedtype/nested/example.go
- analyzer/testdata/src/namedtype/nested/example2.go
- analyzer/testdata/src/namedtype/nested/rules.go
- analyzer/testdata/src/namedtype/rules.go
- analyzer/testdata/src/namedtype/x/nested/element.go
- analyzer/testdata/src/namedtype/y/nested/element.go
> analyzer/testdata: add more Import() tests

- analyzer/testdata/src/extra/file.go
- analyzer/testdata/src/extra/rules.go
- rules.go
> rules.go: add context select->if rule

- analyzer/testdata/src/extra/file.go
- analyzer/testdata/src/extra/rules.go
- rules.go
> improve context.Context select rule

- analyzer/testdata/src/extra/file.go
- analyzer/testdata/src/extra/rules.go
- rules.go
> rules.go: add empty var/const/type decl check

- ruleguard/parser.go
> ruleguard: give error on repeated DSL calls

- ruleguard/parser.go
> ruleguard: use local closures to make code prettier

- ruleguard/runner.go
> ruleguard: make debug submatch printing stable

- go.mod
- go.sum
- ruleguard/debug_test.go
- ruleguard/runner.go
> ruleguard: add debug output tests

- ruleguard/parser.go
- ruleguard/ruleguard_test.go
- ruleguard/typematch/typematch.go
> ruleguard: refactor args parsing + add error testing

- _test/install/binary_gopath/expected2.txt
- _test/install/binary_gopath/test.bash
- _test/install/binary_nogopath/expected2.txt
- _test/install/binary_nogopath/test.bash
- _test/install/gitclone/expected5.txt
- _test/install/gitclone/test.bash
> _test: add tests for -e argument

- ruleguard/quasigo/compile.go
Add source location info to the "only functions with a single non-void results are supported"
compilation error message.
> ruleguard/quasigo: improve "bad ret type" error message

- internal/mvdan.cc/gogrep/gogrep_test.go
> gogrep: add more capture tests

- analyzer/testdata/src/gocritic/f1.go
- analyzer/testdata/src/gocritic/rules.go
> analyzer/testdata: fix emptyStringTest rule for gocritic

- analyzer/testdata/src/filtertest/f1.go
- analyzer/testdata/src/filtertest/linetest4.go
- analyzer/testdata/src/filtertest/rules.go
- analyzer/testdata/src/filtertest/utils.go
- go.mod
- go.sum
- ruleguard/filters.go
- ruleguard/parser.go
> ruleguard: implement Var.Line filter

- README.md
> readme: add one more rule in the examples

- ruleguard/quasigo/compile.go
- ruleguard/quasigo/eval.go
- ruleguard/quasigo/eval_test.go
- ruleguard/quasigo/gen_opcodes.go
- ruleguard/quasigo/opcode_string.go
- ruleguard/quasigo/opcodes.gen.go
- ruleguard/quasigo/testdata/voidfunc/main.go
- ruleguard/ruleguard_error_test.go
Added EvalTest files to simplify the quasigo testing.
> ruleguard/quasigo: implement void funcs

- ruleguard/irprint/irprint.go
This is important for big rule sets that can produce large Go files.
Fixes #326
> ruleguard/irprint: make printed IR ~15% more compact

- analyzer/testdata/src/quasigo/rules.go
- ruleguard/ir_loader.go
- ruleguard/quasigo/compile.go
- ruleguard/quasigo/compile_test.go
- ruleguard/quasigo/disasm.go
- ruleguard/quasigo/eval.go
- ruleguard/quasigo/eval_bench_test.go
- ruleguard/quasigo/eval_test.go
- ruleguard/quasigo/gen_opcodes.go
- ruleguard/quasigo/opcode_string.go
- ruleguard/quasigo/opcodes.gen.go
- ruleguard/quasigo/quasigo.go
- ruleguard/quasigo/quasigo_test.go
- ruleguard/quasigo/testdata/funcs/main.go
- ruleguard/ruleguard_error_test.go
Now it's possible to call one bytecode function from another.
> all: allow calling quasigo functions from quasigo

- .github/workflows/go.yml
- Makefile
- analyzer/analyzer_test.go
- analyzer/testdata/src/generics/rules.go
- analyzer/testdata/src/generics/target.go
- go.mod
- go.sum
- internal/xtypes/xtypes.go
> internal/xtypes: handle new Union and TypeParam types

- rules/refactor.go
- rules/testdata/refactor.go
Just getting myself familiar with the project :)
> rules: add sort.Float64s to sortFuncs

- analyzer/testdata/src/filtertest/f1.go
- analyzer/testdata/src/filtertest/rules.go
- go.mod
- go.sum
- ruleguard/filters.go
- ruleguard/ir/filter_op.gen.go
- ruleguard/ir/gen_filter_op.go
- ruleguard/ir_loader.go
- ruleguard/irconv/irconv.go
> ruleguard: implement Object.IsVariadicParam() filter
